name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --profile=release
    - name: Doc
      run: cargo doc --profile=release
    - name: Run tests
      run: cargo test --verbose --profile=release
    - name: Run tests (slow)
      run: cargo test --verbose
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    - name: Run fuzz ranking
      run: cargo fuzz run ranking --sanitizer=none -- -max_total_time=20 -max_len=9
    - name: Run fuzz unranking
      run: cargo fuzz run unranking --sanitizer=none -- -max_total_time=20 -max_len=128
    - name: Run fuzz bigint-previous-next
      run: cargo fuzz run bigint-previous-next --sanitizer=none -- -max_total_time=20 -max_len=215
    - name: Run fuzz bigint-all
      run: cargo fuzz run bigint-all --sanitizer=none -- -max_total_time=20 -max_len=212
